CREATE TABLE DEPARTMENT (ID BIGINT NOT NULL, NAME VARCHAR(255), PRIMARY KEY (ID))

CREATE TABLE MY_GENERATOR (GEN_NAME VARCHAR(50) NOT NULL, GEN_COUNT DECIMAL(15), PRIMARY KEY (GEN_NAME))

INSERT INTO MY_GENERATOR(GEN_NAME, GEN_COUNT) values ('dep_id', 5)

