CREATE TABLE USERS (ID BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
 EMAIL VARCHAR(255) NOT NULL UNIQUE, PASSWORD CLOB(64000), VERSION INTEGER,
 PRIMARY KEY (ID))

CREATE TABLE POST (ID BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
 CONTENT VARCHAR(255), TITLE VARCHAR(255) NOT NULL UNIQUE,
 VERSION INTEGER, PRIMARY KEY (ID))
--------------------------------------------------------------------------------
INSERT INTO USERS (EMAIL, PASSWORD, VERSION) VALUES (?, ?, ?)
	bind => [, , 1]
SELECT ID, EMAIL, PASSWORD, VERSION FROM USERS