CREATE TABLE DESK (ID BIGINT NOT NULL, FLOOR VARCHAR, PRIMARY KEY (ID))

CREATE TABLE EMPLOYEE (ID BIGINT NOT NULL, full_name VARCHAR,
 DESK_ID BIGINT, PRIMARY KEY (ID))

ALTER TABLE EMPLOYEE ADD CONSTRAINT FK_EMPLOYEE_DESK_ID FOREIGN KEY (DESK_ID) 
REFERENCES DESK (ID)

INSERT INTO DESK (ID, FLOOR) VALUES (?, ?)
	bind => [1, 1/3]

INSERT INTO EMPLOYEE (ID, full_name, DESK_ID) VALUES (?, ?, ?)
	bind => [2, kada, null]

UPDATE EMPLOYEE SET DESK_ID = ? WHERE (ID = ?)
	bind => [1, 2]