CREATE TABLE EMPLOYEE (ID BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
 DTYPE VARCHAR(31), SSN VARCHAR(255) NOT NULL UNIQUE,
 FIRSTNAME VARCHAR(255) NOT NULL UNIQUE, LASTNAME VARCHAR(255) NOT NULL UNIQUE,
 PRIMARY KEY (ID))

CREATE TABLE PARTTIMEEMPLOYEE (ID BIGINT NOT NULL, RATE DECIMAL(15), 
PRIMARY KEY (ID))

CREATE TABLE FULLTIMEEMPLOYEE (ID BIGINT NOT NULL, SALARY DECIMAL(15),
 PRIMARY KEY (ID))

ALTER TABLE PARTTIMEEMPLOYEE ADD CONSTRAINT PARTTIMEEMPLOYEEID FOREIGN KEY (ID) 
REFERENCES EMPLOYEE (ID)

ALTER TABLE FULLTIMEEMPLOYEE ADD CONSTRAINT FULLTIMEEMPLOYEEID FOREIGN KEY (ID) 
REFERENCES EMPLOYEE (ID)
--------------------------------------------------------------------------------
INSERT INTO EMPLOYEE (SSN, FIRSTNAME, LASTNAME, DTYPE) VALUES (?, ?, ?, ?)
	bind => [sfkhsk, sfkhsdf, skdfhsdk, FullTimeEmployee]
INSERT INTO EMPLOYEE (SSN, FIRSTNAME, LASTNAME, DTYPE) VALUES (?, ?, ?, ?)
	bind => [kdfhsk, sdf;ls, sdfls, PartTimeEmployee]
INSERT INTO FULLTIMEEMPLOYEE (SALARY, ID) VALUES (?, ?)
	bind => [0, 1]
INSERT INTO PARTTIMEEMPLOYEE (RATE, ID) VALUES (?, ?)
	bind => [1, 2]
SELECT t0.ID, t0.DTYPE, t0.SSN, t0.FIRSTNAME, t0.LASTNAME, t1.ID, t1.SALARY FROM
 EMPLOYEE t0, FULLTIMEEMPLOYEE t1 WHERE ((t1.ID = t0.ID) AND (t0.DTYPE = ?))
	bind => [FullTimeEmployee]

SELECT t0.ID, t0.DTYPE, t0.SSN, t0.FIRSTNAME, t0.LASTNAME, t1.ID, t1.RATE FROM 
EMPLOYEE t0, PARTTIMEEMPLOYEE t1 WHERE ((t1.ID = t0.ID) AND (t0.DTYPE = ?))
	bind => [PartTimeEmployee]

SELECT DISTINCT DTYPE FROM EMPLOYEE

SELECT t0.ID, t0.DTYPE, t0.SSN, t0.FIRSTNAME, t0.LASTNAME, t1.ID, t1.SALARY FROM
 EMPLOYEE t0, FULLTIMEEMPLOYEE t1 WHERE ((t1.ID = t0.ID) AND (t0.DTYPE = ?))
	bind => [FullTimeEmployee]

SELECT t0.ID, t0.DTYPE, t0.SSN, t0.FIRSTNAME, t0.LASTNAME, t1.ID, t1.RATE FROM
 EMPLOYEE t0, PARTTIMEEMPLOYEE t1 WHERE ((t1.ID = t0.ID) AND (t0.DTYPE = ?))
	bind => [PartTimeEmployee]
