CREATE TABLE RESPOSIBILITY (ID BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
 DESCRIPTION VARCHAR(255), NAME VARCHAR(255) NOT NULL, PRIMARY KEY (ID))

CREATE TABLE EMPLOYEE (ID BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
 FIRSTNAME VARCHAR(255), LASTNAME VARCHAR(255), PRIMARY KEY (ID))

CREATE TABLE EMPLOYEE_RESPOSIBILITY (EMPLOYEE_ID BIGINT NOT NULL, 
RESPONSIBILITY_ID BIGINT NOT NULL, PRIMARY KEY (EMPLOYEE_ID, RESPONSIBILITY_ID))

ALTER TABLE EMPLOYEE_RESPOSIBILITY ADD CONSTRAINT MPLYRSPSRSPNSBLTYD FOREIGN KEY
 (RESPONSIBILITY_ID) REFERENCES RESPOSIBILITY (ID)

ALTER TABLE EMPLOYEE_RESPOSIBILITY ADD CONSTRAINT MPLYRSPSBLITYMPLYD FOREIGN KEY
 (EMPLOYEE_ID) REFERENCES EMPLOYEE (ID)