CREATE TABLE usr_t (ID BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
EMAIL VARCHAR(255), PASSWORD VARCHAR(255), PRIMARY KEY (ID))

CREATE TABLE User_INTRESTS (User_ID BIGINT, INTRESTS VARCHAR(255))
ALTER TABLE User_INTRESTS ADD CONSTRAINT UserINTRESTSUserID
 FOREIGN KEY (User_ID) REFERENCES usr_t (ID)

INSERT INTO usr_t (EMAIL, PASSWORD) VALUES (?, ?)
	bind => [khaled@ap.com, adfs]
INSERT INTO User_INTRESTS (User_ID, INTRESTS) VALUES (?, ?)
	bind => [1, Java]
INSERT INTO User_INTRESTS (User_ID, INTRESTS) VALUES (?, ?)
	bind => [1, Jakarta EE]

SELECT ID, EMAIL, PASSWORD FROM usr_t
*****lazy loading here******
SELECT t0.INTRESTS FROM User_INTRESTS t0 WHERE (t0.User_ID = ?)
	bind => [1]

SELECT ID, EMAIL, PASSWORD FROM usr_t

SELECT t0.INTRESTS FROM User_INTRESTS t0 WHERE (t0.User_ID = ?)
	bind => [1]
DELETE FROM User_INTRESTS WHERE ((User_ID = ?) AND (INTRESTS = ?))
	bind => [1, Java]
EclipseLink, version: Eclipse Persistence Services - 4.0.0.v202210051929
SELECT ID, EMAIL, PASSWORD FROM usr_t
SELECT t0.INTRESTS FROM User_INTRESTS t0 WHERE (t0.User_ID = ?)
	bind => [1]
SELECT ID, EMAIL, PASSWORD FROM usr_t
SELECT t0.INTRESTS FROM User_INTRESTS t0 WHERE (t0.User_ID = ?)
	bind => [1]
INSERT INTO User_INTRESTS (User_ID, INTRESTS) VALUES (?, ?)
	bind => [1, MicroProfile]
INSERT INTO User_INTRESTS (User_ID, INTRESTS) VALUES (?, ?)
	bind => [1, Helidon]
SELECT ID, EMAIL, PASSWORD FROM usr_t
SELECT t0.INTRESTS FROM User_INTRESTS t0 WHERE (t0.User_ID = ?)
	bind => [1]
