CREATE TABLE DEPARTMENT (ID BIGINT NOT NULL, NAME VARCHAR(255), PRIMARY KEY (ID))
CREATE SEQUENCE DEP_SEQ INCREMENT BY 50 START WITH 50

--------test---------
VALUES(NEXT VALUE FOR DEP_SEQ)
INSERT INTO DEPARTMENT (ID, NAME) VALUES (?, ?)
	bind => [1, management]
--------test---------

SELECT ID, NAME FROM DEPARTMENT

