CREATE SCHEMA IF NOT EXISTS PED;

CREATE TABLE IF NOT EXISTS PED.STD( ST_id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,first_name VARCHAR(50) NOT NULL ,last_name VARCHAR(50) NOT NULL, dof Date NOT NULL, PRIMARY KEY(ST_id));

CREATE SCHEMA IF NOT EXISTS HR;

CREATE TABLE IF NOT EXISTS HR.PROF(PROF_id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL, first_name VARCHAR(50) NOT NULL, last_name VARCHAR(50) NOT NULL, SSN VARCHAR(20) NOT NULL UNIQUE, PRIMARY KEY(PROF_id));


