CREATE DATABASE HR;
CREATE DATABASE PED;
USE PED;
CREATE TABLE ST( ST_id BIGINT NOT NULL AUTO_INCREMENT,first_name VARCHAR(50) NOT NULL ,last_name VARCHAR(50) NOT NULL, dof Date NOT NULL, PRIMARY KEY(ST_id));
USE HR;
create table HR.PROF(PROF_id BIGINT NOT NULL AUTO_INCREMENT,first_name VARCHAR(50) NOT NULL, last_name VARCHAR(50) NOT NULL, SSN VARCHAR(20) NOT NULL UNIQUE, PRIMARY KEY(PROF_id));
