CREATE TABLE EMPLOYEE (ID BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
 DTYPE VARCHAR(31), SSN VARCHAR(255) NOT NULL UNIQUE,
 FIRSTNAME VARCHAR(255) NOT NULL, LASTNAME VARCHAR(255) NOT NULL,
 DEP_ID BIGINT, PRIMARY KEY (ID))

CREATE TABLE FULLTIMEEMPLOYEE (ID BIGINT NOT NULL, ANNUALWAGE DECIMAL(15),
 PRIMARY KEY (ID))

CREATE TABLE PARTTIMEEMPLOYEE (ID BIGINT NOT NULL, HOURLYRATE DECIMAL(15),
 PRIMARY KEY (ID))

CREATE TABLE DEPARTMENT (ID BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
 NAME VARCHAR(255) NOT NULL UNIQUE, PRIMARY KEY (ID))

ALTER TABLE EMPLOYEE ADD CONSTRAINT FK_EMPLOYEE_DEP_ID FOREIGN KEY (DEP_ID)
 REFERENCES DEPARTMENT (ID)

ALTER TABLE FULLTIMEEMPLOYEE ADD CONSTRAINT FULLTIMEEMPLOYEEID FOREIGN KEY (ID) 
REFERENCES EMPLOYEE (ID)

ALTER TABLE PARTTIMEEMPLOYEE ADD CONSTRAINT PARTTIMEEMPLOYEEID FOREIGN KEY (ID)
 REFERENCES EMPLOYEE (ID)
INSERT INTO DEPARTMENT (NAME) VALUES (?)
	bind => [IT]
INSERT INTO EMPLOYEE (SSN, FIRSTNAME, LASTNAME, DEP_ID, DTYPE) VALUES (?, ?, ?, ?, ?)
	bind => [ksdlfs, ksdlf, sdfljsdf, 1, PartTimeEmployee]
INSERT INTO PARTTIMEEMPLOYEE (HOURLYRATE, ID) VALUES (?, ?)
	bind => [1, 1]
SELECT DISTINCT DTYPE FROM EMPLOYEE
SELECT t0.ID, t0.DTYPE, t0.SSN, t0.FIRSTNAME, t0.LASTNAME, t0.DEP_ID, t1.ID,
 t1.HOURLYRATE FROM EMPLOYEE t0, PARTTIMEEMPLOYEE t1 WHERE ((t1.ID = t0.ID) 
AND (t0.DTYPE = ?))
	bind => [PartTimeEmployee]
SELECT t0.ID, t0.DTYPE, t0.SSN, t0.FIRSTNAME, t0.LASTNAME, t0.DEP_ID, t1.ID,
 t1.HOURLYRATE FROM EMPLOYEE t0, PARTTIMEEMPLOYEE t1 WHERE ((t1.ID = t0.ID) 
AND (t0.DTYPE = ?))
	bind => [PartTimeEmployee]
