CREATE TABLE FULLTIMEEMPLOYEE (ID BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
 SSN VARCHAR(255) NOT NULL UNIQUE, ANNUALWAGE DECIMAL(15),
 FIRSTNAME VARCHAR(255) NOT NULL, LASTNAME VARCHAR(255) NOT NULL,
 DEP_ID BIGINT, PRIMARY KEY (ID))

CREATE TABLE PARTTIMEEMPLOYEE (ID BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
 SSN VARCHAR(255) NOT NULL UNIQUE, FIRSTNAME VARCHAR(255) NOT NULL,
 HOURLYRATE DECIMAL(15), LASTNAME VARCHAR(255) NOT NULL, DEP_ID BIGINT,
 PRIMARY KEY (ID))

CREATE TABLE DEPARTMENT (ID BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
 NAME VARCHAR(255) NOT NULL UNIQUE, PRIMARY KEY (ID))

ALTER TABLE FULLTIMEEMPLOYEE ADD CONSTRAINT FLLTIMEEMPLOYEEDPD FOREIGN KEY
 (DEP_ID) REFERENCES DEPARTMENT (ID)

ALTER TABLE PARTTIMEEMPLOYEE ADD CONSTRAINT PRTTIMEEMPLOYEEDPD FOREIGN KEY
 (DEP_ID) REFERENCES DEPARTMENT (ID)
--------------------------------------------------------------------------------
INSERT INTO DEPARTMENT (NAME) VALUES (?)
	bind => [IT]
INSERT INTO PARTTIMEEMPLOYEE (SSN, FIRSTNAME, HOURLYRATE, LASTNAME, DEP_ID) 
VALUES (?, ?, ?, ?, ?)
	bind => [ksdlfs, ksdlf, 1, sdfljsdf, 1]

SELECT ID, SSN, FIRSTNAME, HOURLYRATE, LASTNAME, DEP_ID FROM PARTTIMEEMPLOYEE