CREATE TABLE EMPLOYEE (ID BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
 DTYPE VARCHAR(31), SSN VARCHAR(255) NOT NULL UNIQUE,
 FIRSTNAME VARCHAR(255) NOT NULL, LASTNAME VARCHAR(255) NOT NULL,
 DEP_ID BIGINT, ANNUALWAGE DECIMAL(15), HOURLYRATE DECIMAL(15), PRIMARY KEY (ID))

CREATE TABLE DEPARTMENT (ID BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
 NAME VARCHAR(255) NOT NULL UNIQUE, PRIMARY KEY (ID))

ALTER TABLE EMPLOYEE ADD CONSTRAINT FK_EMPLOYEE_DEP_ID FOREIGN KEY (DEP_ID)
 REFERENCES DEPARTMENT (ID)

INSERT INTO DEPARTMENT (NAME) VALUES (?)
	bind => [IT]

INSERT INTO EMPLOYEE (SSN, FIRSTNAME, HOURLYRATE, LASTNAME, DEP_ID, DTYPE) 
VALUES (?, ?, ?, ?, ?, ?)
	bind => [ksdlfs, ksdlf, 1, sdfljsdf, 1, PartTimeEmployee]

SELECT ID, DTYPE, SSN, FIRSTNAME, LASTNAME, DEP_ID, HOURLYRATE, ANNUALWAGE FROM
EMPLOYEE

SELECT ID, DTYPE, SSN, FIRSTNAME, LASTNAME, DEP_ID, HOURLYRATE FROM EMPLOYEE 
WHERE (DTYPE = ?)
	bind => [PartTimeEmployee]
