CREATE TABLE BOOK (ID BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
 ISBN VARCHAR(255), NBROFP INTEGER, TITLE VARCHAR(255), PRIMARY KEY (ID))

CREATE TABLE AUTHOR (ID BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
 FIRSTNAME VARCHAR(255), LASTNAME VARCHAR(255), NICKNAME VARCHAR(255),
 PRIMARY KEY (ID))

CREATE TABLE GENRE (BOOK_ID BIGINT, name VARCHAR(255))

CREATE TABLE AUTHOR_BOOK (BOOK_ID BIGINT NOT NULL, AUTHOR_ID BIGINT NOT NULL,
 PRIMARY KEY (BOOK_ID, AUTHOR_ID))

ALTER TABLE GENRE ADD CONSTRAINT FK_GENRE_BOOK_ID
 FOREIGN KEY (BOOK_ID) REFERENCES BOOK (ID)

ALTER TABLE AUTHOR_BOOK ADD CONSTRAINT AUTHOR_BOOKBOOK_ID
 FOREIGN KEY (BOOK_ID) REFERENCES BOOK (ID)

ALTER TABLE AUTHOR_BOOK ADD CONSTRAINT AUTHORBOOKAUTHORID
 FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR (ID)

