CREATE TABLE DEPARTMENT (ID BIGINT NOT NULL, NAME VARCHAR, PRIMARY KEY (ID))

CREATE TABLE EMPLOYEE (ID BIGINT NOT NULL, FIRSTNAME VARCHAR, LASTNAME VARCHAR, DEP_ID BIGINT NOT NULL, PRIMARY KEY (ID))

ALTER TABLE EMPLOYEE ADD CONSTRAINT FK_EMPLOYEE_DEP_ID FOREIGN KEY (DEP_ID) REFERENCES DEPARTMENT (ID)

INSERT INTO DEPARTMENT (ID, NAME) VALUES (?, ?)
	bind => [1, management]


SELECT ID, NAME FROM DEPARTMENT


INSERT INTO EMPLOYEE (ID, FIRSTNAME, LASTNAME, DEP_ID) VALUES (?, ?, ?, ?)
	bind => [2, mohamed, ali, 1]

